import {
    Column,
    CreateDateColumn,
    Entity,
    JoinColumn,
    ManyToOne,
    PrimaryGeneratedColumn,
    UpdateDateColumn,
} from 'typeorm';
import { Tenant } from './tenant.entity';
import { Employee } from './employee.entity';
import { User } from './user.entity';
import { ReviewTemplate } from './review-template.entity';

/**
 * A review that is due, or was.
 *
 * ⚠️ `origin` is the load-bearing column. The scheduler that generates upcoming
 * cycles filters `origin = 'system'`, which makes an ad-hoc review structurally
 * incapable of delaying, replacing or satisfying a scheduled one — the client's
 * requirement, enforced by the data model rather than by convention
 * (docs/HRM.md §13.1).
 *
 * Both can be open at once, and an ad-hoc review has identical consequences: it
 * can promote, grant an increment, or start a PIP.
 */
@Entity('review_cycles')
export class ReviewCycle {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    tenantId: number;

    @Column()
    employeeId: number;

    /** Position in the SCHEDULED sequence. Null for ad-hoc reviews. */
    @Column({ type: 'int', nullable: true })
    sequenceNo: number | null;

    /** probation_3m | quarterly | ad_hoc */
    @Column({ type: 'varchar', length: 24 })
    cycleType: string;

    /** system = generated by the scheduler; manual = raised by a person. */
    @Column({ type: 'varchar', length: 16, default: 'system' })
    origin: string;

    /**
     * promotion_consideration | performance_concern | post_training_assessment |
     * disciplinary | pre_exit
     */
    @Column({ type: 'varchar', length: 48, nullable: true })
    adHocReason: string | null;

    @Column({ type: 'date' })
    periodFrom: string;

    @Column({ type: 'date' })
    periodTo: string;

    @Column({ type: 'date' })
    dueDate: string;

    @Column({ type: 'int', nullable: true })
    reviewerUserId: number | null;

    @Column({ type: 'int', nullable: true })
    templateId: number | null;

    /** scheduled | in_progress | submitted | approved | closed | skipped */
    @Column({ type: 'varchar', length: 24, default: 'scheduled' })
    status: string;

    @Column({ type: 'text', nullable: true })
    skipReason: string | null;

    @Column({ type: 'int', nullable: true })
    createdBy: number | null;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @ManyToOne(() => Tenant, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'tenant_id' })
    tenant: Tenant;

    @ManyToOne(() => Employee, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'employee_id' })
    employee: Employee;

    @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true })
    @JoinColumn({ name: 'reviewer_user_id' })
    reviewer: User | null;

    @ManyToOne(() => ReviewTemplate, { onDelete: 'SET NULL', nullable: true })
    @JoinColumn({ name: 'template_id' })
    template: ReviewTemplate | null;
}
